name: Rust

on:
  push:
    branches:
      - main
    tags-ignore:
      - "**-action-build-**"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-on-windows:

    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4.2.0
        env:
          cache-name: cache-cargo
        with:
          path: |
            ./target
            ~/.cargo
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: build-debug
        run: cargo build
      - name: build-release
        run: cargo build --release

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          # Artifact name
          name: windows-build
          # A file, directory or wildcard pattern that describes what to upload
          path: ./target/*/multiply_or_release.exe

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./target/release/multiply_or_release.exe"
          token: ${{ secrets.RELEASE_TOKEN }}
          commit: "refs/heads/main"
          prerelease: true
          tag: ${{ runner.os }}-action-build-${{ github.sha }}
          artifactErrorsFailBuild: false


  build-on-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4.2.0
        env:
          cache-name: cache-cargo
        with:
          path: |
            ./target
            ~/.cargo
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: pre-build
        run: sudo apt-get install -y libudev-dev libasound2-dev

      - name: build-debug
        run: cargo build
      - name: build-release
        run: cargo build --release

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          # Artifact name
          name: linux-build
          # A file, directory or wildcard pattern that describes what to upload
          path: ./target/*/multiply_or_release
          # The desired behavior if no files are found using the provided path.

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./target/release/multiply_or_release"
          token: ${{ secrets.RELEASE_TOKEN }}
          commit: "refs/heads/main"
          prerelease: true
          tag: ${{ runner.os }}-action-build-${{ github.sha }}
          artifactErrorsFailBuild: false